name: docs

on:
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs
        run: |
          docker run --rm \
            -v "$PWD:/workdir" \
            -w /workdir \
            quay.io/terraform-docs/terraform-docs:0.24.0-amd64 \
            markdown --config /workdir/.terraform-docs.yml /workdir

      - name: Push changes back to PR
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet -- README.md; then
            git add README.md
            git commit -m "terraform-docs: automated action"
            git push
          else
            echo "README.md already up to date"
          fi
